### ISSUE TITLE
Resolvable Bugs

### ISSUE THREAD

**Issue by ashwinexe** [KATURIABHIRAM/BBC_NEWS_WEBPAGE_PROJECT#1]
A good web project, here are some of the issues I found :
- files are named AS extensions itself, hence browser won't load most of them
- Images are missing although their source is mentioned in the source, perhaps you might forgot to push them in the repository.

**Comment by KATURIABHIRAM** [comment]
This message caught attention ashwin . Will check the issue accordingly and update it as soon as possible .
